DECLARE
  EMPL EMPLOYEES%ROWTYPE;
BEGIN
  SELECT * INTO EMPL
  FROM EMPLOYEES
  WHERE EMPLOYEE_ID=100;

  DBMS_OUTPUT.PUT_LINE(EMPL.FIRST_NAME);
EXCEPTION
  WHEN EX1 THEN
    NULL;
  WHEN EX2 THEN
    NULL;
  WHEN OTHERS THEN
    NULL;
END;