SET SERVEROUTPUT ON;

DECLARE
  EMPL EMPLOYEES%ROWTYPE;
BEGIN
  SELECT * INTO EMPL
  FROM EMPLOYEES
  WHERE 
    --EMPLOYEE_ID=1000;  -- Produce NO_DATA_FOUND
    EMPLOYEE_ID > 1;     -- Produce TOO_MANY_ROWS

  DBMS_OUTPUT.PUT_LINE(EMPL.FIRST_NAME);
EXCEPTION
-- NO_DATA_FOUND      ORA-01403
-- TOO_MANY_ROWS      ORA-01422
-- ZERO_DIVIDE
-- DUP_VAL_ON_INDEX

  
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('ERROR, EMPLEADO INEXISTENTE');
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR, DEMASIADOS EMPLEADOS');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR INDEFINIDO');
END;