SET SERVEROUTPUT ON

DECLARE 
/* OPERADORES MAS HABITUALES

    +   SUNA
    -   RESTA
    /   DIVISIÓN
    *   MULTIPLICACIÓN
    **  EXPONENTE
    ||  CONCATENAR
*/

  X NUMBER;
  Z NuMBER:=10;
  A VARCHAR2(100):='EXAMPLE';
  D DATE:='10-01-1990';

BEGIN
  DBMS_OUTPUT.PUT_LINE(SYSDATE);
  DBMS_OUTPUT.PUT_LINE(D+1);
END;