SET SERVEROUTPUT ON
DECLARE
  x VARCHAR2(50);
  MAYUS VARCHAR2(100);
  FECHA DATE;
  Z NUMBER := 109.80;
BEGIN
  x := 'Ejemplo';
  DBMS_OUTPUT.PUT_LINE(SUBSTR(x,1,3));
  MAYUS:=UPPER(x);
  DBMS_OUTPUT.PUT_LINE(MAYUS);
  FECHA:=SYSDATE;
  DBMS_OUTPUT.PUT_LINE(FECHA);

  DBMS_OUTPUT.PUT_LINE(FLOOR(Z));
END;
/

-- Funciones no permitidas en el uso de PL:
-- FUNCIONES DE GRUPO   COUNT, AVG
-- DECODE