DECLARE
  SALARIO NUMBER;
  NOMBRE EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
  SELECT   -- SOLO PUEDE DEVOLVER UNA FILA
    SALARY, FIRST_NAME INTO SALARIO, NOMBRE
  FROM
    EMPLOYEES
  WHERE
    EMPLOYEE_ID = 100;
  dbms_output.put_line(SALARIO);
  DBMS_OUTPUT.PUT_LINE(NOMBRE);
END;