DECLARE
  SALARIO NUMBER;
  NOMBRE EMPLOYEES.FIRST_NAME%TYPE;
  EMPLEADO EMPLOYEES%ROWTYPE;
BEGIN
  SELECT   -- SOLO PUEDE DEVOLVER UNA FILA
    * INTO EMPLEADO
  FROM
    EMPLOYEES
  WHERE
    EMPLOYEE_ID = 100;
  dbms_output.put_line(EMPLEADO.SALARY*100);
  DBMS_OUTPUT.PUT_LINE(EMPLEADO.FIRST_NAME);
END;