SET SERVEROUTPUT ON

BEGIN
  FOR i IN 5..15 LOOP  -- PLS_INTEGER
    DBMS_OUTPUT.PUT_LINE(i);
  END LOOP;
END;
/

BEGIN
  FOR i IN  REVERSE 5..15 LOOP -- PLS_INTEGER
    DBMS_OUTPUT.PUT_LINE(i);
  END LOOP;
END;
/

DECLARE
  i VARCHAR2(100):='AAAAA';
BEGIN
  FOR i IN  REVERSE 5..15 LOOP -- PLS_INTEGER
    DBMS_OUTPUT.PUT_LINE(i);
    EXIT WHEN i = 10;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE(i);
END;
/
