/*
1. PRÁCTICA 1

• VAMOS A CREAR LA TABLA DE MULTIPLICAR DEL 1 AL 10, CON LOS TRES TIPOS DE BUCLES: LOOP, WHILE Y FOR
*/

SET SERVEROUTPUT ON;

DECLARE
  i NUMBER := 0;
  j NUMBER;
BEGIN
  LOOP
    i := i + 1;
    j := 0;
    LOOP
      j := j + 1;
      DBMS_OUTPUT.PUT_LINE(i || ' X ' || j || ' = ' || i*j);
      EXIT WHEN j = 10;
    END LOOP;
    EXIT WHEN i = 10;
  END LOOP;
END;
/

DECLARE
  i NUMBER := 1;
  j NUMBER := 1;
BEGIN
  WHILE i <= 10 LOOP
    j := 1;
    WHILE j <= 10 LOOP
      DBMS_OUTPUT.PUT_LINE(i || ' X ' || j || ' = ' || i*j);
      j := j + 1;
    END LOOP;
    j := j + 1;
  END LOOP;
END;
/

BEGIN
  FOR i IN 1..10 LOOP
    FOR j IN 1..10 LOOP
      DBMS_OUTPUT.PUT_LINE(i || ' X ' || j || ' = ' || i*j);
    END LOOP;
  END LOOP;
END;
/


/*
2. PRÁCTICA 2-
• CREAR UNA VARIABLE LLAMADA TEXTO DE TIPO VARCHAR2(100).

• PONER ALGUNA FRASE

• MEDIANTE UN BUCLE, ESCRIBIR LA FRASE AL REVÉS, USAMOS EL BUCLE WHILE
*/

DECLARE
  TEXTO VARCHAR2(100);
  TEXTO_AL_REVES VARCHAR2(100) := '';
  i PLS_INTEGER := 0;
BEGIN
  TEXTO := 'La vida es bonita';
  WHILE LENGTH(TEXTO) != i LOOP
    TEXTO_AL_REVES := TEXTO_AL_REVES || SUBSTR(TEXTO,
                          LENGTH(TEXTO) - i, 1
                         );
    i := i + 1;                  
  END LOOP;
  DBMS_OUTPUT.PUT_LINE(TEXTO_AL_REVES);
END;
/

/*

3. PRÁCTICA 3

• USANDO LA PRÁCTICA ANTERIOR, SI EN EL TEXTO APARECE EL CARÁCTER "x" DEBE SALIR DEL BUCLE. ES IGUAL EN MAYÚSCULAS O MINÚSCULAS.

• DEBEMOS USAR LA CLÁUSULA EXIT.
*/

DECLARE
  TEXTO VARCHAR2(100);
  LETRA VARCHAR2(1);
  TEXTO_AL_REVES VARCHAR2(100) := '';
  i PLS_INTEGER := 0;
BEGIN
  TEXTO := 'La vida x es bonita';
  WHILE LENGTH(TEXTO) != i LOOP
    LETRA := SUBSTR(TEXTO, LENGTH(TEXTO) - i, 1);
    EXIT WHEN UPPER(LETRA) = 'X';
    TEXTO_AL_REVES := TEXTO_AL_REVES || LETRA;
    i := i + 1;                  
  END LOOP;
  DBMS_OUTPUT.PUT_LINE(TEXTO_AL_REVES);
END;
/

/*

4. PRÁCTICA 4

• DEBEMOS CREAR UNA VARIABLE LLAMADA NOMBRE

• DEBEMOS PINTAR TANTOS ASTERISCOS COMO LETRAS TENGA EL NOMBRE.
  USAMOS UN BUCLE FOR   

    • POR EJEMPLO ALBERTO → *******

    • O POR EJEMPLO PEDRO → *****
*/

DECLARE
  NOMBRE VARCHAR2(50);
  ASTERISCOS NOMBRE%TYPE := '';
BEGIN
  NOMBRE := 'Misael';
  FOR i IN 1..LENGTH(NOMBRE) LOOP
    ASTERISCOS := ASTERISCOS || '*';
  END LOOP;
  DBMS_OUTPUT.PUT_LINE(NOMBRE || ' -> ' || ASTERISCOS);
END;
/

/*

5. PRÁCTICA 5

• CREAMOS DOS VARIABLES NUMÉRICAS, "inicio y fin"

• LAS INICIALIZAMOS CON ALGÚN VALOR:

• DEBEMOS SACAR LOS NÚMEROS QUE SEAN MÚLTIPLOS DE 4 DE ESE RANGO
*/

DECLARE
  inicio NUMBER;
  fin NUMBER;
  MULTIPLO_DE_4 VARCHAR2(100) := '';
BEGIN
  inicio := 1;
  fin := 10;
  FOR i IN inicio..fin LOOP
    IF i MOD 4 = 0 THEN
      DBMS_OUTPUT.PUT_LINE(i);
    END IF;
  END LOOP;
END;
/
